// Generated by CoffeeScript 1.3.3
var AvatarsIO, crypto, fs, request;

request = require('request');

fs = require('fs');

crypto = require('crypto');

AvatarsIO = (function() {

  function AvatarsIO() {}

  AvatarsIO.accountId = '';

  AvatarsIO.accessToken = '';

  AvatarsIO.upload = function(path, identifier, callback) {
    var _this = this;
    if ('function' === typeof identifier) {
      callback = identifier;
      identifier = '';
    }
    return fs.readFile(path, function(err, buffer) {
      return request({
        url: 'http://avatars.io/v1/token',
        method: 'POST',
        headers: {
          'x-client_id': _this.accountId,
          'Authorization': "OAuth " + _this.accessToken
        },
        body: JSON.stringify({
          data: {
            filename: path,
            md5: crypto.createHash('md5').update(buffer).digest('hex'),
            size: buffer.length,
            path: identifier
          }
        })
      }, function(err, res, body) {
        body = JSON.parse(body);
        if (!body.data.upload_info) {
          return callback(false, body.data.url);
        }
        return request({
          url: body.data.upload_info.upload_url,
          method: 'PUT',
          headers: {
            'Authorization': body.data.upload_info.signature,
            'Date': body.data.upload_info.date,
            'Content-Type': body.data.upload_info.content_type,
            'x-amz-acl': 'public-read'
          },
          body: buffer
        }, function() {
          return request({
            url: "http://avatars.io/v1/token/" + body.data.id + "/complete",
            method: 'POST',
            headers: {
              'x-client_id': _this.accountId,
              'Authorization': "OAuth " + _this.accessToken
            },
            body: ''
          }, function(err, res, body) {
            return callback(false, JSON.parse(body).data);
          });
        });
      });
    });
  };

  AvatarsIO.avatarUrl = function(service, key) {
    return "http://avatars.io/" + service + "/" + key;
  };

  AvatarsIO.avatarURL = function() {
    return this.avatarUrl.apply(this, arguments);
  };

  AvatarsIO.avatar_url = function() {
    return this.avatarUrl.apply(this, arguments);
  };

  return AvatarsIO;

})();

module.exports = AvatarsIO;
